insert into endereco (estado, cidade, bairro, rua, numero, cep) values('SC', 'Joinville', 'Petropolis', 'Manoel de Souza', 100, 89208782);
insert into endereco (estado, cidade, bairro, rua, numero, cep) values('PR', 'Curitiba', 'Guarujá', 'Afonso Padilha', 1508, 87408569);
insert into marca (nome, ativo) values('Motorola', 'S');
insert into marca (nome, ativo) values('Samsung', 'S');
insert into marca (nome, ativo) values('Nokia', 'N');
insert into categoriaaparelho (nome, ativo) values('Smartphone', 'S');
insert into categoriaaparelho (nome, ativo) values('Televisor', 'S');
insert into categoriaaparelho (nome, ativo) values('Radio', 'N');
insert into aparelho (nome, numeroserie, modelo, ativo, marca_id, categoriaaparelho_id) values('Moto E', 'XT589', 'Moto E 5 Plus', 'S', 1, 1);
insert into aparelho (nome, numeroserie, modelo, ativo, marca_id, categoriaaparelho_id) values('TV Samsung', '85964756', 'LED 4k SM589', 'N', 2, 2);
insert into servicos (tiposervico, nome, descricao, ativo) values('Manutencao', 'Troca de tela', 'Desmontagem e troca da tela, remontagem e teste do aparelho.', 'S');
insert into servicos (tiposervico, nome, descricao, ativo) values('Limpeza', 'Limpeza do aparelho', 'Desmontagem e limpeza de componentes, remontagem e teste do aparelho.', 'N');
insert into funcionario (cargo, setor, salario, dataadmissao, numeroct, pis, datademissao) values('Suporte', 'Atedimento', 2500.00, '2019-05-02', '58635964', '14529687369', '2019-12-20');
insert into pessoa (nome, cpf, rg, datanascimento, sexo, telefone, celular, email, profissao, tipomorada, tipopessoa, ativo, funcionario_id, endereco_id) values ('Leonardo Paterno', '09612435979', '6655574', '2019-11-12', 'M', '47 3466 4444', '47 9 99455951', 'leo', 'Suporte', 'casa', 'PF', 'S', 1, 1);
insert into pessoa (nome, cpf, rg, datanascimento, sexo, telefone, celular, email, profissao, tipomorada, tipopessoa, ativo, endereco_id) values ('Paterno Leo', '09612435979', '6655574', '2019-11-12', 'M', '47 3466 4444', '47 9 99455951', 'paterno@gmail.com', 'Suporte', 'casa', 'PF', 'S', 1);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total) values(1,'teste de insert', '', '2019-08-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, 150);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(2,'teste de insert', '', '2019-08-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(2,'teste de insert', '', '2019-01-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(3,'teste de insert', '', '2019-01-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(4,'teste de insert', '', '2019-01-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(5,'teste de insert', '', '2019-01-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(6,'teste de insert', '', '2019-01-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(7,'teste de insert', '', '2019-01-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(8,'teste de insert', '', '2019-01-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(9,'teste de insert', '', '2019-01-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(10,'teste de insert', '', '2019-01-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(11,'teste de insert', '', '2019-01-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(12,'teste de insert', '', '2019-01-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(13,'teste de insert', '', '2019-01-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(14,'teste de insert', '', '2019-01-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);

insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(15,'teste de insert', '', '2019-02-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(16,'teste de insert', '', '2019-02-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(17,'teste de insert', '', '2019-02-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(18,'teste de insert', '', '2019-02-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(19,'teste de insert', '', '2019-02-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(20,'teste de insert', '', '2019-02-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(21,'teste de insert', '', '2019-02-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(22,'teste de insert', '', '2019-02-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(23,'teste de insert', '', '2019-02-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(24,'teste de insert', '', '2019-02-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);

insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(25,'teste de insert', '', '2019-03-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(26,'teste de insert', '', '2019-03-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(27,'teste de insert', '', '2019-03-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);

insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(28,'teste de insert', '', '2019-04-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(29,'teste de insert', '', '2019-04-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(30,'teste de insert', '', '2019-04-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(31,'teste de insert', '', '2019-04-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(31,'teste de insert', '', '2019-04-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);

insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(33,'teste de insert', '', '2019-05-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(34,'teste de insert', '', '2019-05-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(35,'teste de insert', '', '2019-05-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(36,'teste de insert', '', '2019-05-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(37,'teste de insert', '', '2019-05-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(38,'teste de insert', '', '2019-05-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(39,'teste de insert', '', '2019-05-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(40,'teste de insert', '', '2019-05-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);

insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(41,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(42,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(43,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(44,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(45,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(46,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(47,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(48,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(49,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(50,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(51,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(52,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(53,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(54,'teste de insert', '', '2019-06-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);

insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(55,'teste de insert', '', '2019-07-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(56,'teste de insert', '', '2019-07-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(57,'teste de insert', '', '2019-07-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);

insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(58,'teste de insert', '', '2019-08-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(59,'teste de insert', '', '2019-08-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(60,'teste de insert', '', '2019-08-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(61,'teste de insert', '', '2019-08-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(62,'teste de insert', '', '2019-08-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(63,'teste de insert', '', '2019-08-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(64,'teste de insert', '', '2019-08-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(65,'teste de insert', '', '2019-08-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(66,'teste de insert', '', '2019-08-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);

insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(67,'teste de insert', '', '2019-09-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(68,'teste de insert', '', '2019-09-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(69,'teste de insert', '', '2019-09-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(70,'teste de insert', '', '2019-09-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(71,'teste de insert', '', '2019-09-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(72,'teste de insert', '', '2019-09-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(73,'teste de insert', '', '2019-09-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(74,'teste de insert', '', '2019-09-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(75,'teste de insert', '', '2019-09-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);

insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(76,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(76,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(78,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(79,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(80,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(81,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(82,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(83,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(84,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(85,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(86,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(87,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(88,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(89,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(90,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(91,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(92,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(93,'teste de insert', '', '2019-10-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);

insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(94,'teste de insert', '', '2019-11-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(95,'teste de insert', '', '2019-11-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(96,'teste de insert', '', '2019-11-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(97,'teste de insert', '', '2019-11-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(98,'teste de insert', '', '2019-11-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(99,'teste de insert', '', '2019-11-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(100,'teste de insert', '', '2019-11-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(101,'teste de insert', '', '2019-11-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(102,'teste de insert', '', '2019-11-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(103,'teste de insert', '', '2019-11-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(104,'teste de insert', '', '2019-11-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);

insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(106,'teste de insert', '', '2019-12-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(106,'teste de insert', '', '2019-12-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(107,'teste de insert', '', '2019-12-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(108,'teste de insert', '', '2019-12-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(109,'teste de insert', '', '2019-12-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(110,'teste de insert', '', '2019-12-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into ordemservico (numeroos, descproblema, descsolucao, dataabertura, dataprazo, datafechamento, statusos, pessoa_id, ativo, aparelho_id, servicos_id, total ) values(102,'teste de insert', '', '2019-12-21', '2019-08-27', null, 'AB', 1, 'S', 1, 1, null);
insert into login (email, senha, pessoa_id, ordemservico_id) values('leo', '87d9bb400c0634691f0e3baaf1e2fd0d', 1, (select max(id) from ordemservico));
insert into login (email, senha, pessoa_id, ordemservico_id) values('paternoleo@gmail.com', '87d9bb400c0634691f0e3baaf1e2fd0d', 2, (select max(id) from ordemservico));




