-- MySQL Script generated by MySQL Workbench
-- Mon Jun 10 22:09:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OrdemServico
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `OrdemServico` ;

-- -----------------------------------------------------
-- Schema OrdemServico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OrdemServico` DEFAULT CHARACTER SET utf8 ;
USE `OrdemServico` ;

-- -----------------------------------------------------
-- Table `OrdemServico`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`endereco` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT COMMENT 'Atributo chave primária responsável por identificar os atributos da tabela.',
  `rua` VARCHAR(60) NOT NULL COMMENT 'Atributo responsável  por receber o nome da rua.',
  `bairro` VARCHAR(45) NOT NULL COMMENT 'Atributo responsável por receber o nome do Bairro.',
  `cidade` VARCHAR(50) NOT NULL COMMENT 'Atrituo responsável por receber o nome da Cidade',
  `numero` VARCHAR(4) NOT NULL COMMENT 'Atrituo responsável por receber o numero do endereço.',
  `cep` VARCHAR(8) NOT NULL COMMENT 'Atrituo responsável por receber o número do CEP.',
  `estado` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `numerocarteiratrabalho` VARCHAR(8) NOT NULL,
  `PIS` VARCHAR(11) NOT NULL,
  `salario` FLOAT NOT NULL,
  `cargo` VARCHAR(30) NULL,
  `setor` VARCHAR(30) NULL,
  `salario` DOUBLE NULL,
  `dataadmissao` DATE NULL,
  `datademissao` DATE NULL,
  PRIMARY KEY (`idfuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `datanascimento` VARCHAR(8) NOT NULL,
  `rg` VARCHAR(7) NULL,
  `profissao` VARCHAR(75) NULL,
  `endereco_idendereco` INT NOT NULL,
  `funcionario_idfuncionario` INT NOT NULL,
  `sexo` VARCHAR(1) NULL,
  `telefone` VARCHAR(14) NULL,
  `celular` VARCHAR(16) NULL,
  `email` VARCHAR(50) NULL,
  `profissao` VARCHAR(45) NULL,
  `tipomorada` VARCHAR(4) NULL,
  PRIMARY KEY (`idpessoa`),
  INDEX `fk_pessoa_endereco1_idx` (`endereco_idendereco` ASC) VISIBLE,
  INDEX `fk_pessoa_funcionario1_idx` (`funcionario_idfuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_endereco1`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `OrdemServico`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_funcionario1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `OrdemServico`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`marca` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`marca` (
  `marca` INT NOT NULL AUTO_INCREMENT,
  `nomemarca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`categoriaaparelho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`categoriaaparelho` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`categoriaaparelho` (
  `categoriaaparelho` INT NOT NULL AUTO_INCREMENT,
  `tipocategoria` VARCHAR(45) NOT NULL,
  `descricaocategoria` VARCHAR(200) NULL,
  PRIMARY KEY (`categoriaaparelho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`registroaparelho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`registroaparelho` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`registroaparelho` (
  `idregistroaparelho` INT NOT NULL AUTO_INCREMENT,
  `nomeaparelho` VARCHAR(45) NOT NULL,
  `numerodeserie` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `marca_marca` INT NOT NULL,
  `categoriaaparelho_categoriaaparelho` INT NOT NULL,
  PRIMARY KEY (`idregistroaparelho`),
  INDEX `fk_registroaparelho_marca1_idx` (`marca_marca` ASC) VISIBLE,
  INDEX `fk_registroaparelho_categoriaaparelho1_idx` (`categoriaaparelho_categoriaaparelho` ASC) VISIBLE,
  CONSTRAINT `fk_registroaparelho_marca1`
    FOREIGN KEY (`marca_marca`)
    REFERENCES `OrdemServico`.`marca` (`marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registroaparelho_categoriaaparelho1`
    FOREIGN KEY (`categoriaaparelho_categoriaaparelho`)
    REFERENCES `OrdemServico`.`categoriaaparelho` (`categoriaaparelho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`ordemservico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`ordemservico` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`ordemservico` (
  `numeroos` INT(11) NOT NULL,
  `observacoes` VARCHAR(250) NULL,
  `registroaparelho_idregistroaparelho` INT NOT NULL,
  INDEX `fk_ordemservico_registroaparelho1_idx` (`registroaparelho_idregistroaparelho` ASC) VISIBLE,
  PRIMARY KEY (`numeroos`),
  CONSTRAINT `fk_ordemservico_registroaparelho1`
    FOREIGN KEY (`registroaparelho_idregistroaparelho`)
    REFERENCES `OrdemServico`.`registroaparelho` (`idregistroaparelho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`perfil` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `tipoperfil` BINARY(1) NOT NULL,
  `nometipoperfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`login` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT COMMENT 'Atributo chave primaria resposável por receber o identificador dos atributos na tabela.',
  `email` VARCHAR(45) NOT NULL COMMENT 'Atrituo responsável por receber o e-mail registrado para o cliente.',
  `senha` VARCHAR(16) NOT NULL COMMENT 'Atrituo responsável por receber a senha de acesso ao sistema para o usuário.',
  `pessoa_idpessoa` INT NOT NULL,
  `perfil_idperfil` INT NOT NULL,
  `ordemservico_numeroos` INT(11) NOT NULL,
  PRIMARY KEY (`idlogin`),
  INDEX `fk_login_pessoa1_idx` (`pessoa_idpessoa` ASC) VISIBLE,
  INDEX `fk_login_ordemservico1_idx` (`ordemservico_numeroos` ASC) VISIBLE,
  INDEX `fk_login_perfil1_idx` (`perfil_idperfil` ASC) VISIBLE,
  CONSTRAINT `fk_login_pessoa1`
    FOREIGN KEY (`pessoa_idpessoa`)
    REFERENCES `OrdemServico`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_ordemservico1`
    FOREIGN KEY (`ordemservico_numeroos`)
    REFERENCES `OrdemServico`.`ordemservico` (`numeroos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `OrdemServico`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`servicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`servicos` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`servicos` (
  `idservico` INT NOT NULL AUTO_INCREMENT,
  `nometiposervico` VARCHAR(30) NOT NULL,
  `nomeservico` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idservico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`orcamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`orcamento` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`orcamento` (
  `numeroorcamento` INT NOT NULL AUTO_INCREMENT,
  `precoorcamento` FLOAT NOT NULL,
  `ordemservico_numeroos` INT(11) NOT NULL,
  PRIMARY KEY (`numeroorcamento`),
  INDEX `fk_orcamento_ordemservico1_idx` (`ordemservico_numeroos` ASC) VISIBLE,
  CONSTRAINT `fk_orcamento_ordemservico1`
    FOREIGN KEY (`ordemservico_numeroos`)
    REFERENCES `OrdemServico`.`ordemservico` (`numeroos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`controle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`controle` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`controle` (
  `idcontrole` INT NOT NULL AUTO_INCREMENT,
  `statuscontrole` BINARY(1) NOT NULL,
  `orcamento_numeroorcamento` INT NOT NULL,
  `ordemservico_numeroos` INT(11) NOT NULL,
  PRIMARY KEY (`idcontrole`),
  INDEX `fk_controleos_orcamento1_idx` (`orcamento_numeroorcamento` ASC) VISIBLE,
  INDEX `fk_controleos_ordemservico1_idx` (`ordemservico_numeroos` ASC) VISIBLE,
  CONSTRAINT `fk_controleos_orcamento1`
    FOREIGN KEY (`orcamento_numeroorcamento`)
    REFERENCES `OrdemServico`.`orcamento` (`numeroorcamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_controleos_ordemservico1`
    FOREIGN KEY (`ordemservico_numeroos`)
    REFERENCES `OrdemServico`.`ordemservico` (`numeroos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`pecascategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`pecascategoria` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`pecascategoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `tipocategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`pecasestoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`pecasestoque` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`pecasestoque` (
  `idpeca` INT NOT NULL AUTO_INCREMENT,
  `nomepeca` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(30) NOT NULL,
  `quantidadeestoque` INT(11) NOT NULL,
  `pecascategoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idpeca`),
  INDEX `fk_pecasestoque_pecascategoria1_idx` (`pecascategoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_pecasestoque_pecascategoria1`
    FOREIGN KEY (`pecascategoria_idcategoria`)
    REFERENCES `OrdemServico`.`pecascategoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`statusos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`statusos` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`statusos` (
  `status` INT NOT NULL AUTO_INCREMENT,
  `nomestatus` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `ordemservico_numeroos` INT(11) NOT NULL,
  PRIMARY KEY (`status`),
  INDEX `fk_statusos_ordemservico1_idx` (`ordemservico_numeroos` ASC) VISIBLE,
  CONSTRAINT `fk_statusos_ordemservico1`
    FOREIGN KEY (`ordemservico_numeroos`)
    REFERENCES `OrdemServico`.`ordemservico` (`numeroos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`ordemservicopecasestoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`ordemservicopecasestoque` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`ordemservicopecasestoque` (
  `ordemservico_numeroos` INT(11) NOT NULL,
  `pecasestoque_idpeca` INT NOT NULL,
  `quantidadecotada` INT(11) NOT NULL,
  PRIMARY KEY (`ordemservico_numeroos`, `pecasestoque_idpeca`),
  INDEX `fk_ordemservico_has_pecasestoque_pecasestoque1_idx` (`pecasestoque_idpeca` ASC) VISIBLE,
  INDEX `fk_ordemservico_has_pecasestoque_ordemservico1_idx` (`ordemservico_numeroos` ASC) VISIBLE,
  CONSTRAINT `fk_ordemservico_has_pecasestoque_ordemservico1`
    FOREIGN KEY (`ordemservico_numeroos`)
    REFERENCES `OrdemServico`.`ordemservico` (`numeroos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordemservico_has_pecasestoque_pecasestoque1`
    FOREIGN KEY (`pecasestoque_idpeca`)
    REFERENCES `OrdemServico`.`pecasestoque` (`idpeca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`ordemservicoservicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`ordemservicoservicos` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`ordemservicoservicos` (
  `ordemservico_numeroos` INT(11) NOT NULL,
  `servicos_idservico` INT NOT NULL,
  `observacoes` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`ordemservico_numeroos`, `servicos_idservico`),
  INDEX `fk_ordemservico_has_servicos_servicos1_idx` (`servicos_idservico` ASC) VISIBLE,
  INDEX `fk_ordemservico_has_servicos_ordemservico1_idx` (`ordemservico_numeroos` ASC) VISIBLE,
  CONSTRAINT `fk_ordemservico_has_servicos_ordemservico1`
    FOREIGN KEY (`ordemservico_numeroos`)
    REFERENCES `OrdemServico`.`ordemservico` (`numeroos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordemservico_has_servicos_servicos1`
    FOREIGN KEY (`servicos_idservico`)
    REFERENCES `OrdemServico`.`servicos` (`idservico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`tipocontrole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`tipocontrole` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`tipocontrole` (
  `idtipocontrole` INT NOT NULL AUTO_INCREMENT,
  `nometipocontrole` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipocontrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrdemServico`.`tipocontrolecontrole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrdemServico`.`tipocontrolecontrole` ;

CREATE TABLE IF NOT EXISTS `OrdemServico`.`tipocontrolecontrole` (
  `tipocontrole_idtipocontrole` INT NOT NULL,
  `controle_idcontrole` INT NOT NULL,
  PRIMARY KEY (`tipocontrole_idtipocontrole`, `controle_idcontrole`),
  INDEX `fk_tipocontrole_has_controle_controle1_idx` (`controle_idcontrole` ASC) VISIBLE,
  INDEX `fk_tipocontrole_has_controle_tipocontrole1_idx` (`tipocontrole_idtipocontrole` ASC) VISIBLE,
  CONSTRAINT `fk_tipocontrole_has_controle_tipocontrole1`
    FOREIGN KEY (`tipocontrole_idtipocontrole`)
    REFERENCES `OrdemServico`.`tipocontrole` (`idtipocontrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipocontrole_has_controle_controle1`
    FOREIGN KEY (`controle_idcontrole`)
    REFERENCES `OrdemServico`.`controle` (`idcontrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
